# h2 database web으로 확인
spring:
  h2:
    console:
      enabled: true
      path: /h2-console   # web으로 데이터 확인

  jpa:
    database: h2
    show_sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/spring-db;MODE=MySQL; # embedded Mode: db 데이터 저장 위치: ~/spring-db (파일로 저장함)
    username: sa
    password: sa

  # .sql 파일 읽어들이게 설정
  sql:
    init:
      mode: always
      # schema-locations: classpath:schema.sql
